apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: #{Octopub.Kustomize.Cluster.Namespace}
resources:
- ../../base

patches:
  - target:
      kind: Deployment
      name: octopub-audit-deployment
    path: octopub-audits-deployment.yaml
  - target:
      kind: Service
      name: octopub-audit-cluster-ip
    path: octopub-audits-service.yaml
  - target: 
      kind: Ingress
      name: octopub-ingress-audits
    path: octopub-ingress.yaml


configMapGenerator:
  - name: audit-service-env-vars
    behavior: merge
    env: variables.properties

images:
  - name: ghcr.io/octopussamples/octopub-audit-microservice
    newName: #{Octopus.Action.Package[octopub-audit-microservice].PackageId}
    newTag: #{Octopus.Action.Package[octopub-audit-microservice].PackageVersion}
