- op: replace
  path: /spec/template/spec/containers/0/ports/0/containerPort
  value: #{Project.Frontend.ContainerPort}

- op: replace
  path: /spec/template/spec/containers/0/env/0/name
  value: #{Project.Frontend.ClientIdentifier}

- op: replace
  path: /spec/template/spec/containers/0/env/1/name
  value: #{Project.Frontend.FeatureToggleSlug}