ingress:
  enabled: true
  className: #{Project.Ingress.ClassName}
  annotations: {


     }
  hosts:
    - host: #{Project.Host.Name}
      paths:
        - path: /
          pathType: Prefix
          
service:
  type: ClusterIP
  port: 8080

image:
  repository: #{Octopus.Action.Package[octopub-frontend].PackageId}
  tag: #{Octopus.Action.Package[octopub-frontend].PackageVersion}