database:
  migrateOnStartup: true
  
ingress:
  enabled: true
  className: #{Project.Ingress.ClassName}
  annotations: {
     }
  hosts:
    - host: #{Project.Host.Name}
      paths:
        - path: /api/audits
          pathType: Prefix
        
service:
  type: ClusterIP
  port: 10000
  
image:
  repository: #{Octopus.Action.Package[octopub-audit-microservice].PackageId}
  tag: #{Octopus.Action.Package[octopub-audit-microservice].PackageVersion}  