name: Java SBOM Build
description: Builds an SBOM for a Java project
inputs:
  path:
    required: true
    description: The path to the project
  output_path:
    required: true
    description: The output path for the SBOM file

runs:
  using: "composite"
  steps:
    - name: Install CycloneDX
      run: npm install --global @cyclonedx/cyclonedx-npm
      shell: bash

    - name: Generate SBOM
      run: |
        npm install
        cyclonedx-npm --ignore-npm-errors --output-file bom.json
        mkdir -p ${{ inputs.output_path }}
        mv bom.json ${{ inputs.output_path }}/bom.json
      shell: bash
      working-directory: ${{ inputs.path }}