name: Build Scripts
permissions:
  contents: write
  packages: write
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!.github/badges/*'
      - '!README.md'
      - '!octopus/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Scripts
        uses: ./github/script
        with:
          run_number: ${{ github.run_number }}
          octopus_url: ${{ secrets.OCTOPUS_URL }}
          octopus_apikey: ${{ secrets.OCTOPUS_API_KEY }}
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script_directory: octopub-log-scanner